name: Automerge

on:
  # Handles events in the PR's lifecycle (opened, updated, reopened, etc.)
  pull_request:
    types: [opened, synchronize, reopened]

  # Handles the signal that the CI tests have finished
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_FILTER_AUTHOR: "red-hat-konflux"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: ""
