name: Automerge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR associated with the commit
        id: get_pr
        uses: stefanbuck/github-event-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Automerge
        if: ${{ steps.get_pr.outputs.pull_request_author == 'red-hat-konflux[bot]' && steps.get_pr.outputs.pull_request_number != '' }}
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_PULL_REQUEST: ${{ steps.get_pr.outputs.pull_request_number }}
          MERGE_METHOD: "squash"
          MERGE_FILTER_AUTHOR: "red-hat-konflux[bot]"
          MERGE_DELETE_BRANCH: "true"
